<?php
/**
 * Writes the .htaccess generated by Tools::generateHtaccess() without booting PrestaShop.
 *
 * Usage: php generate.php <classes/Tools.php> <output .htaccess> <scenario> <physical_uri> <friendly URLs: 1|0> <cache control: 1|0>
 *
 * Scenarios:
 *   single   one shop on shop.test, multistore disabled
 *   virtual  multistore on shop.test: a main shop and a shop on the virtual URI "shop2/"
 *   domains  multistore: shop.test, second.test (SSL domain secure.second.test), media servers media1-3.test
 *   manydomains multistore: shop.test and 399 other domains
 *   physicals multistore: shop.test on <physical_uri>, second.test on <physical_uri>alt/ (a link to the same folder)
 */
declare(strict_types=1);

[, $toolsFile, $output, $scenario, $physicalUri, $friendlyUrls, $cacheControl] = $argv;

define('_PS_ROOT_DIR_', __DIR__);

function shopUrl(int $idShop, string $domain, string $domainSsl, string $virtualUri, string $physicalSuffix = ''): object
{
    global $physicalUri;

    return (object) ['id_shop' => $idShop, 'domain' => $domain, 'domain_ssl' => $domainSsl, 'physical_uri' => $physicalUri . $physicalSuffix, 'virtual_uri' => $virtualUri];
}

class Configuration
{
    public static function get($key, $idLang = null, $idShopGroup = null, $idShop = null)
    {
        global $friendlyUrls;

        return $key === 'PS_REWRITING_SETTINGS' ? (int) $friendlyUrls : 0;
    }

    public static function getMultiShopValues($key)
    {
        global $scenario;

        $mediaServers = ['PS_MEDIA_SERVER_1' => 'media1.test', 'PS_MEDIA_SERVER_2' => 'media2.test', 'PS_MEDIA_SERVER_3' => 'media3.test'];

        return [1 => $scenario === 'domains' ? ($mediaServers[$key] ?? '') : ''];
    }
}

class Shop
{
    public static function isFeatureActive()
    {
        global $scenario;

        return $scenario !== 'single';
    }
}

class ShopUrl
{
    public static function getShopUrls()
    {
        global $scenario;

        switch ($scenario) {
            case 'single':
                return [shopUrl(1, 'shop.test', 'shop.test', '')];
            case 'virtual':
                return [shopUrl(1, 'shop.test', 'shop.test', ''), shopUrl(2, 'shop.test', 'shop.test', 'shop2/')];
            case 'domains':
                return [shopUrl(1, 'shop.test', 'shop.test', ''), shopUrl(2, 'second.test', 'secure.second.test', '')];
            case 'manydomains':
                $shopUrls = [shopUrl(1, 'shop.test', 'shop.test', '')];
                for ($idShop = 2; $idShop <= 400; ++$idShop) {
                    $shopUrls[] = shopUrl($idShop, "shop$idShop.many-domains.test", "shop$idShop.many-domains.test", '');
                }

                return $shopUrls;
            case 'physicals':
                return [shopUrl(1, 'shop.test', 'shop.test', ''), shopUrl(2, 'second.test', 'second.test', '', 'alt/')];
        }
        throw new InvalidArgumentException("Unknown scenario $scenario");
    }
}

class Hook
{
    public static function exec(...$args)
    {
        return null;
    }
}

require $toolsFile;

class Tools extends ToolsCore
{
}

if (!Tools::generateHtaccess($output, (int) $friendlyUrls, (int) $cacheControl, '', false, false, 0)) {
    fwrite(STDERR, "Could not write $output\n");
    exit(1);
}
